# Generated by Django 4.0 on 2022-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
